site_name: Miraclys

repo_url: https://github.com/Miraclys/Numerical-Analysis

repo_name: Numerical Analysis

# language: 'en'

theme:
  name: material
  # logo: assets/鲨鱼.jpg
  favicon: assets/鲨鱼.jpg
  language: en
  
  palette:
    primary: 'deep purple'
    accent: 'deep purple'

  features:
    # - header.autohide
      # - navigation.instant 好像一开始是因为这一个插件，所以数学公式没有办法正确显示
      # - navigation.instant.prefetch
      - navigation.tabs

nav:
  - Home: index.md
  - Lecture1: lecture1/lecture1.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - JavaScript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  # - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# extra:
#   social:
#     - type: 'github'
#       link: 'https://github.com/Miraclys'