site_name: Miraclys

repo_url: https://github.com/Miraclys/Numerical-Analysis

repo_name: Numerical Analysis

# language: 'en'

theme:
  name: material
  # custom_dir: overrides
  # logo: assets/鲨鱼.jpg
  favicon: assets/鲨鱼.jpg
  language: en
  
  palette:
    # - primary: 'white'
    # - accent: 'white'
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    # - header.autohide
      # - navigation.instant 好像一开始是因为这一个插件，所以数学公式没有办法正确显示
      # - navigation.instant.prefetch
      - navigation.tabs

nav:
  - Home: index.md
  - Lecture1: lecture1/lecture1.md
  - Lecture2: 
    - 'Chapter 2': lecture2/index.md
    - 'The Bisection Method': lecture2/bisection.md
    - 'Fixed Point Method': lecture2/fixed_point.md
    - "Newton's Method": lecture2/Newtons.md 
    # - 'Fixed-Point Iteration': lecture2/fixed-point-iteration.md
    # - 'Newton's Method and Its Extensions': lecture2/newton.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - JavaScript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  # - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# extra:
#   social:
#     - type: 'github'
#       link: 'https://github.com/Miraclys'